# Optimized Configuration Generated by Advanced Parameter Optimizer
# Generated on: 2025-06-07 18:39:27.296058

get_optimized_config <- function() {
  return(list(
    # Basic calculation parameters
    base_per_diem = 52.1153654632187,
    mileage_rates = c(0.636619061097109, 0.739544158684605, 0.518604879793777),
    receipt_rates = c(0.418279690220294, 0.550050807622028, 0.603233533636507, 0.192347396873923),
    
    # Tier boundaries
    mileage_tiers = c(77.363573984502, 398.427665465335),
    receipt_tiers = c(52.4071273792267, 393.616200128839, 1185.3345635616),
    
    # Threshold values
    receipt_threshold = 705.063645736828,
    efficiency_threshold = 213.969910483109,
    miles_threshold = 337.69293355599,
    
    # Feature engineering thresholds
    efficiency_zones = c(100, 180, 220, 300),
    spending_categories = c(75, 120),
    sweet_spot_duration = c(4, 6),
    
    # Cluster definition parameters
    cluster_boundaries = list(
      very_short_high_eff = c(1.5, 500),
      long_low_eff = c(8, 50),
      medium_high_spend = c(3, 5, 1500),
      medium_high_eff = c(4, 7, 150, 800),
      long_high_spend = c(8, 1200)
    ),
    
    # Multipliers and adjustments
    cluster_multipliers = c(1.01566467065751, 0.985793590008604, 0.993533296227976, 0.965800090973539, 0.971424079461676, 1.03565905771526),
    vacation_bonus_multiplier = 0.937847711084682,
    vacation_base_multiplier = 0.977643319351364,
    five_day_multiplier = 1.10461953575543,
    receipt_threshold_multiplier = 1.07318995251003,
    efficiency_threshold_multiplier = 0.938856801831129,
    miles_threshold_multiplier = 0.93025153547156,
    
    # Advanced features
    interaction_coeff = -0.00497920710557241,
    log_bonus_coeff = 6.94094355050645,
    bug_base_bonus = 6.11569135676808,
    bug_multiplier = 0.00472448163790963,
    
    # Enhanced rounding bug parameters
    bug_cents_values = c(49, 99, 1, 51)
  ))
}
